# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Kyle Qian
tagline:             'student @ brown university'
description:         'programmer, scholar, baller, classical violinist, culinary enthusiast'
url:                 http://lanyon.getpoole.com
baseurl:             ''
paginate:            5
paginate_path:       "page:num"
plugins:             [jekyll-paginate]

# About/contact
author:
  name:              Kyle Qian
  url:               kqian5.github.io
  email:             kyle_qian@brown.edu

# Custom vars
version:             1.0.0

excerpt_separator: <!--more-->