# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Kyle Qian
tagline:             'student @ brown university'
description:         'programmer, scholar, big baller, classical violinist, culinary enthusiast, sheng ji extraordinaire'
url:                 http://lanyon.getpoole.com
baseurl:             ''
paginate:            5
paginate_path:       "page:num"
plugins:             
  - jekyll-paginate
  - jekyll-seo-tag

# About/contact
author:
  name:              Kyle Qian
  url:               kqian5.github.io
  email:             kyle_qian@brown.edu

# Custom vars
version:             1.0.0

excerpt_separator: <!--more-->

seo:
  name: Kyle Qian
  type: Person
url: https://kyle-qian.com
social:
  name: Kyle Qian
  links:
    - https://www.facebook.com/kyle.qian.7
    - https://github.com/kqian5
    - https://www.linkedin.com/in/kyle-qian/